FROM python:3.12


WORKDIR /app


COPY requirements-dev.txt ./
RUN pip install --no-cache-dir -r requirements-dev.txt



EXPOSE 8000


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000","--reload"]